### ISSUE TITLE
paypal 2FA still works

### ISSUE THREAD

**Issue by wjcarpenter** [DuBistKomisch/jakebarnes#1]
Not an issue, per se. I wanted to let you know I just used the hosted version of your paypal 2FA tool (and your guide), and it still works (November 2018). Thanks for putting in the effort to figure it out and host it.

BTW, whoever is in charge of the 2FA stuff at paypal must be pretty disorganized:

- the sort-of hidden link you posted still works
- various bits of text on paypal's web site still say you can set up the proprietary app as a security key, but there's no direct path to it
- if you have more than ~10 security keys in your history, you can't activate a new one (even the phone number type) unless you remove some
- there is no way to remove some
- I spoke with paypal support and she described how to get to the "manage security keys" link on their web site ... except there was no such link at the place she directed me to (we went round and round for a couple of minutes about how I could not find any way to remove any old security keys)
- she offered to remove my security keys for me, but warned me it was all-or-nothing and I would have to set it up again (fine by me) ... but it only removed my mobile number entry and left all of the others in place (at least that gave me a "slot" to add my new fake proprietary entry
- for the very first time, I installed the paypal mobile app ... after userid/password, it told me they couldn't use the old type of security key, but I could get a new digital one at their web site ... that led me back to my existing list of security keys; we've all been there

Anyhow, what a screwed up outfit, at least on this topic. Thanks again for helping out the world.

**Comment by DuBistKomisch** [comment]
Thanks, not sure what the issue is though!

**Comment by wjcarpenter** [comment]
Sorry, there wasn't an issue. I couldn't find another reliable way to give you a thank you message.

BTW, somewhere along the way, Paypal finally get around to offering MFA with standard TOTP applications. I guess they either hired someone who fixed things, or they got tired of paying Symantec, or something.

Thanks again for your original work.
